services:
  - type: web
    name: cucia-frontend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: ""
    startCommand: ""
    ports:
      - port: 3001
